src/main/urls.py
from django.urls import path

from . import views


app_name = "main"

urlpatterns = [
        path("", views.index, name="index"),
        path("new/", views.new_item, name="new"),
        path("del/", views.del_item, name="del"),
        path("test/", views.test, name="test"),
        path("<str:name>", views.index, name="index"),
]

src/to_do_list/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("main/", include("main.urls")),

]

src/main/models.py
from django.db import models


class Items(models.Model):
    item = models.CharField(max_length=1024)

    def __str__(self):
        return f"{self.item}"

    def __repr__(self):
        return f"{self.item}"

src/main/views.py
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Items


class NewItem(forms.Form):
    item = forms.CharField(label="New Item")


class DelItem(forms.Form):
    item = forms.IntegerField(label="Item Num? ")


def index(request, name: str = ""):
    """Print All Items"""
    all_items = [i[1] for i in Items.objects.values_list()]
    return render(
        request,
        "main/index.html",
        {
            "items": all_items,
        },
    )


def new_item(request):
    """If method is post:
        Extract The Item From The HttpResponse && Create A New One.
    else:
        View The Form For Creating A New Item.
    """
    if request.method == "POST":
        form = NewItem(request.POST)
        form.is_valid()
        item = Items(item=form.cleaned_data["item"])
        item.save()
        return HttpResponseRedirect(reverse("main:index"))

    return render(
        request,
        "main/new_item.html",
        {
            "form": NewItem,
        },
    )


def del_item(request):
    """If method is post:
        Extract The Item's Num From The HttpResponse && Get Its Id Then Delete
        Its Object && If Num==0: Delete All Objects.
    else:
        View The Form For Deleting An Item.
    """
    all_items = Items.objects.values_list()
    if request.method == "POST":
        form = DelItem(request.POST)
        form.is_valid()
        item = form.cleaned_data["item"]

        if item == 0:
            Items.objects.all().delete()

        elif 0 < item <= len(all_items):
            """ Check For Boundaries. """
            item -= 1
            Items.objects.get(id=all_items[item][0]).delete()

        else:
            return render(
                request,
                "main/del_item.html",
                {
                    "form": DelItem,
                    "error": item,
                },
            )

        return HttpResponseRedirect(reverse("main:index"))

    return render(
        request,
        "main/del_item.html",
        {
            "form": DelItem,
        },
    )



def test(request, name: str = ""):
    return HttpResponse("Django Is Running OK!")

src/main/templates/main/del_item.html
{% extends "main/layout.html" %}

{% block body %}
    <form action="{% url 'main:del' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Delete" class="submit"> 
    </form>
    <a href="{% url 'main:index' %}"> Cancel </a>
    {% if  error  %}
        <p class="error" style="padding:0px;"> {{ error }} is not in ur items </p>
    {% endif %}
    <h6 class="note"> For clearing the whole lilst enter: 0 </h6>
{% endblock %}

src/main/templates/main/index.html
{% extends "main/layout.html" %}

{% block body %}
    <h1> Welcom to STDL:
       <br> Simple To Do List
    </h1>
    {% if items %}
        <ol>
            {% for item in items %}
                <li> {{ item }} </li>
            {% endfor %}
        </ol>
    {% else %}
        <p class="note"> Good job, Ur list is empty!</p>
    {% endif %}
    <a href="{% url 'main:new' %}"> New Item</a>
    <a href="{% url 'main:del' %}"> Del Item</a>
{% endblock %}

src/main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<html lang=en>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=10">
            

        <title> STDL </title>
        <link href="{% static 'main/styles.css' %}" rel="stylesheet">

    </head>

    <body>
        <dev id="main_dev">
        {% block body %}
        {% endblock %}
        </dev>
    </body>

</html>

src/main/templates/main/new_item.html
{% extends "main/layout.html" %}

{% block body %}
    <form action="{% url 'main:new' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="New" class="submit">
    </form>
    <a href="{% url 'main:index' %}"> Cancel </a>
{% endblock %}